-- ============================================================
--  V13. 회원 배송지 주소록
--  회원이 배송지를 저장해 두고 결제 때 골라 쓴다.
--  휴대폰은 애플리케이션에서 암호화해 저장한다(평문 금지).
-- ============================================================

CREATE TABLE member_address (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                BIGINT       NOT NULL REFERENCES member(id) ON DELETE CASCADE,

    -- 사용자가 붙이는 별칭 (예: 집, 회사). 선택.
    label                    VARCHAR(50),
    receiver_name            VARCHAR(100) NOT NULL,
    -- 암호화해 저장한다. 평문으로 넣지 않는다.
    receiver_phone_encrypted VARCHAR(500),

    zipcode                  VARCHAR(10)  NOT NULL,
    addr1                    VARCHAR(300) NOT NULL,
    addr2                    VARCHAR(300),

    is_default               BOOLEAN      NOT NULL DEFAULT false,

    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_member_address_member ON member_address (member_id);

-- 회원당 기본 배송지는 하나만 존재할 수 있다.
CREATE UNIQUE INDEX uq_member_address_default
    ON member_address (member_id) WHERE is_default;
