-- ============================================================
--  V1. 상품 도메인
--  제품은 지금 하나지만 처음부터 다제품 구조로 만든다 (기획서 §8).
--  금액은 전부 원 단위 정수다. 한국 통화는 소수점을 쓰지 않는다.
-- ============================================================

CREATE TABLE product (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 주소에 쓰는 영문 이름. 공개 URL 이 /products/{slug} 이므로 바꾸면 링크가 깨진다.
    slug             VARCHAR(120)  NOT NULL UNIQUE,
    name_ko          VARCHAR(200)  NOT NULL,
    name_en          VARCHAR(200),
    subtitle         VARCHAR(300),
    -- 리치 텍스트 에디터 입력. 저장 시 서버에서 HTML 살균한 결과만 들어간다.
    description_html TEXT,
    price            INTEGER       NOT NULL CHECK (price >= 0),
    discount_price   INTEGER       CHECK (discount_price >= 0),
    weight_g         INTEGER       CHECK (weight_g > 0),
    servings         INTEGER       CHECK (servings > 0),
    -- 옵션이 있는 상품은 옵션별 재고를 쓴다. 이 값은 옵션 없는 상품용이다.
    stock            INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0),
    thumbnail_key    VARCHAR(500),
    is_featured      BOOLEAN       NOT NULL DEFAULT FALSE,
    sort_order       INTEGER       NOT NULL DEFAULT 0,
    visible          BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT product_discount_le_price
        CHECK (discount_price IS NULL OR discount_price <= price)
);

CREATE INDEX idx_product_visible_sort ON product (visible, sort_order);
CREATE INDEX idx_product_featured     ON product (is_featured) WHERE is_featured;

COMMENT ON COLUMN product.slug          IS '주소에 쓸 영문 이름';
COMMENT ON COLUMN product.is_featured   IS '메인 페이지 노출 여부';
COMMENT ON COLUMN product.visible       IS '사이트 노출 여부. false 면 공개 API 가 반환하지 않는다';


-- 용량·맛 확장 대비 (기획서 §13-11). 옵션이 없으면 행이 없다.
CREATE TABLE product_option (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT      NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    name        VARCHAR(120) NOT NULL,
    -- 기준가 대비 증감액. 500g 이 -3000, 2kg 이 +9000 같은 식.
    price_delta INTEGER     NOT NULL DEFAULT 0,
    stock       INTEGER     NOT NULL DEFAULT 0 CHECK (stock >= 0),
    sort_order  INTEGER     NOT NULL DEFAULT 0,
    visible     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id, name)
);

CREATE INDEX idx_product_option_product ON product_option (product_id);


CREATE TABLE product_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    -- S3 오브젝트 키. 앱 서버가 파일을 서빙하지 않는다 (기획서 §10).
    image_key  VARCHAR(500) NOT NULL,
    alt_text   VARCHAR(300),
    type       VARCHAR(20)  NOT NULL DEFAULT 'DETAIL'
               CHECK (type IN ('MAIN', 'DETAIL', 'LIFESTYLE')),
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_image_product ON product_image (product_id, sort_order);


-- 영양성분. 법정 표시사항이므로 이미지가 아니라 이 값으로 DOM 텍스트를 만든다.
CREATE TABLE nutrition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT       NOT NULL UNIQUE REFERENCES product (id) ON DELETE CASCADE,
    serving_size_g  NUMERIC(8,2) NOT NULL,
    kcal            NUMERIC(8,2),
    carb_g          NUMERIC(8,2),
    protein_g       NUMERIC(8,2),
    fat_g           NUMERIC(8,2),
    sugar_g         NUMERIC(8,2),
    sodium_mg       NUMERIC(8,2),
    -- 위 항목 외 추가 성분. {"식이섬유_g": 1.2} 형태.
    extra_json      JSONB,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- 원재료명 및 함량. 알레르기 유발물질 표시 의무 대응.
CREATE TABLE ingredient (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    name       VARCHAR(200) NOT NULL,
    percentage NUMERIC(5,2) CHECK (percentage >= 0 AND percentage <= 100),
    origin     VARCHAR(120),
    allergen   VARCHAR(200),
    sort_order INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_ingredient_product ON ingredient (product_id, sort_order);


-- 그 밖의 법정 표시사항. 상품마다 1행.
CREATE TABLE product_label (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT       NOT NULL UNIQUE REFERENCES product (id) ON DELETE CASCADE,
    food_type          VARCHAR(120),   -- 식품유형
    shelf_life         VARCHAR(200),   -- 소비기한 표기
    storage_method     VARCHAR(300),   -- 보관방법
    manufacturer       VARCHAR(200),   -- 제조원
    manufacturer_addr  VARCHAR(300),
    seller             VARCHAR(200),   -- 판매원
    seller_addr        VARCHAR(300),
    customer_service   VARCHAR(120),   -- 소비자상담실 연락처
    package_material   VARCHAR(200),
    extra_notice       TEXT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- 외부 판매 채널 링크. 자사몰과 병행 판매하는 경우에 쓴다.
CREATE TABLE purchase_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    channel    VARCHAR(20)  NOT NULL
               CHECK (channel IN ('NAVER', 'COUPANG', 'OWN', 'OTHER')),
    url        VARCHAR(1000) NOT NULL,
    label      VARCHAR(120),
    sort_order INTEGER      NOT NULL DEFAULT 0,
    visible    BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_purchase_link_product ON purchase_link (product_id, sort_order);
