-- 메인 FEATURES(네 칸) 전용 테이블.
--
-- 설정 키-값으로 두면 칸을 늘리거나 순서를 바꿀 수 없고 사진도 문자열로 들고 있어야 한다.
-- 배너처럼 행으로 관리한다 — 대표가 관리자에서 추가·수정·삭제·순서 변경을 한다.
--
-- 본문을 비우면 화면에서 아무 문장도 나가지 않는다. 다만 auto_nutrition_body 가 켜진 칸은
-- 상품 영양성분(1회 제공량·탄수화물·열량)으로 문장을 만들어 채운다 — 숫자를 코드에 박지 않기 위해서다.

CREATE TABLE main_feature (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(100) NOT NULL,
    body                TEXT         NOT NULL DEFAULT '',
    -- 사진 저장 키. 비면 화면이 기본 사진을 쓴다.
    image_key           VARCHAR(500),
    -- 사진 대체 텍스트(접근성). 비면 큰 문구를 대신 읽어준다.
    alt_text            VARCHAR(300),
    auto_nutrition_body BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order          INTEGER      NOT NULL DEFAULT 0,
    visible             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_main_feature_order ON main_feature (visible, sort_order, id);

-- 지금 화면에 나가는 네 칸 (2026-09-14 승인 카피).
INSERT INTO main_feature (title, body, auto_nutrition_body, sort_order) VALUES
    ('국산 멥쌀 한 가지',       '국산 멥쌀만으로 만들었습니다. 원재료명에 멥쌀 한 줄뿐입니다.',                        FALSE, 1),
    ('자극이 적은 담백한 맛',   '고운 입자로 갈아, 조리하면 죽처럼 부드럽고 담백한 맛이 납니다.',                     FALSE, 2),
    ('운동 전후 탄수화물 보충', '',                                                                                  TRUE,  3),
    ('다양한 맞춤 레시피',     '프로틴 파우더, 견과류, 과일 등을 조합해 기호에 맞춰 손쉽게 완성할 수 있습니다.',       FALSE, 4);

-- V23 에서 설정에 넣었던 키는 이 테이블이 대신한다.
DELETE FROM site_setting WHERE key LIKE 'main.feature%';
