-- 메인 화면 팝업 (2026-09-17 승인).
--
-- 대표가 관리자에서 이미지 팝업을 올린다. 메인 화면에 들어오면 떠 있는 팝업이 하나씩 보인다.
-- 노출 기간이 지나면 자동으로 내려간다 (배너와 같은 규칙).

CREATE TABLE popup (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 관리용 제목. 이미지 대체 텍스트로도 쓴다.
    title              VARCHAR(200)  NOT NULL,
    -- 사진 저장 키 (image 모듈). 이미지 팝업이라 필수다.
    image_key          VARCHAR(500)  NOT NULL,
    -- "오늘 하루 보지 않기" 체크 칸을 보여 줄지
    show_hide_today    BOOLEAN       NOT NULL DEFAULT TRUE,
    -- 이동 버튼("자세히 보기")을 보여 줄지. 이미지를 눌러도 같은 곳으로 간다.
    show_link_button   BOOLEAN       NOT NULL DEFAULT FALSE,
    -- 이동할 주소. https:// 로 시작하는 바깥 주소 또는 / 로 시작하는 사이트 안 주소.
    link_url           VARCHAR(1000),
    always_on          BOOLEAN       NOT NULL DEFAULT TRUE,
    start_at           TIMESTAMPTZ,
    end_at             TIMESTAMPTZ,
    sort_order         INTEGER       NOT NULL DEFAULT 0,
    visible            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_popup_period CHECK (always_on OR (start_at IS NOT NULL AND end_at IS NOT NULL AND start_at < end_at))
);

CREATE INDEX idx_popup_active ON popup (visible, sort_order, id);
