-- 상품 상세 페이지 섹션 (2026-09-18).
--
-- 사진형 상세페이지: 관리자가 올린 이미지를 위에서 아래로 "틈 없이" 이어 붙인다.
-- 중간에 영상(유튜브 주소 또는 올린 mp4)과 짧은 글을 끼워 넣을 수 있다.
--
-- ★ 법정 표시사항(영양성분·원재료·표시사항)은 이 섹션이 아니라 기존 텍스트 영역에 그대로 둔다
--   (CLAUDE.md 규칙 2 — 이미지 안의 글자는 검색·접근성에 잡히지 않는다).

CREATE TABLE product_detail_section (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT       NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    -- IMAGE | VIDEO | TEXT
    type            VARCHAR(20)  NOT NULL,
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    visible         BOOLEAN      NOT NULL DEFAULT TRUE,

    -- IMAGE
    image_key       VARCHAR(500),
    alt_text        VARCHAR(300),

    -- VIDEO: 유튜브 주소(video_url) 또는 올린 파일(video_file_key) 중 하나.
    video_url       VARCHAR(1000),
    video_file_key  VARCHAR(500),
    -- 영상 재생 전 보여줄 사진
    thumbnail_key   VARCHAR(500),

    -- TEXT
    heading         VARCHAR(200),
    body            TEXT,

    caption         VARCHAR(500),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_detail_section_type CHECK (type IN ('IMAGE', 'VIDEO', 'TEXT'))
);

CREATE INDEX idx_detail_section_product ON product_detail_section (product_id, sort_order, id);
