-- ============================================================
--  V2. 회원 · 인증 · 배송지
--  개인정보 테이블에는 동의 시각과 파기 예정일(purge_at)을 반드시 둔다.
--  자동 파기 배치가 이 값을 본다 (기획서 §10).
-- ============================================================

CREATE TABLE member (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(320) NOT NULL,
    -- 소셜 가입 회원은 비밀번호가 없다. BCrypt 해시만 저장한다.
    password_hash       VARCHAR(100),
    name                VARCHAR(100) NOT NULL,
    -- 애플리케이션에서 암호화해 저장한다. 평문으로 넣지 않는다.
    phone_encrypted     VARCHAR(500),
    provider            VARCHAR(20)  NOT NULL DEFAULT 'LOCAL'
                        CHECK (provider IN ('LOCAL', 'KAKAO', 'NAVER')),
    provider_id         VARCHAR(200),
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'DORMANT', 'WITHDRAWN')),

    -- 동의 이력. 필수 동의 강제는 가입 로직에서 한다.
    terms_agreed_at     TIMESTAMPTZ,
    privacy_agreed_at   TIMESTAMPTZ,
    marketing_agreed_at TIMESTAMPTZ,
    -- 만 14세 이상 확인 (기획서 6.2)
    age_verified_at     TIMESTAMPTZ,

    -- 로그인 5회 실패 시 10분 잠금
    failed_count        INTEGER      NOT NULL DEFAULT 0,
    locked_until        TIMESTAMPTZ,
    last_login_at       TIMESTAMPTZ,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    withdrawn_at        TIMESTAMPTZ,
    -- 탈퇴 후 법정 보존기간이 끝나는 시점. 배치가 이 날짜를 지나면 파기한다.
    purge_at            TIMESTAMPTZ
);

-- 같은 이메일이라도 제공자가 다르면 다른 계정이다.
CREATE UNIQUE INDEX uq_member_email_provider ON member (email, provider);
CREATE UNIQUE INDEX uq_member_provider_id    ON member (provider, provider_id)
    WHERE provider_id IS NOT NULL;
CREATE INDEX idx_member_purge  ON member (purge_at) WHERE purge_at IS NOT NULL;
CREATE INDEX idx_member_status ON member (status);


CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT       NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    -- 토큰 원문이 아니라 해시를 저장한다. DB 가 유출돼도 토큰을 재사용할 수 없다.
    token_hash VARCHAR(200) NOT NULL UNIQUE,
    user_agent VARCHAR(300),
    ip         VARCHAR(64),
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_token_member ON refresh_token (member_id);
CREATE INDEX idx_refresh_token_expiry ON refresh_token (expires_at);


CREATE TABLE address (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT       NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    label           VARCHAR(60),
    recipient       VARCHAR(100) NOT NULL,
    phone_encrypted VARCHAR(500) NOT NULL,
    zipcode         VARCHAR(10)  NOT NULL,
    addr1           VARCHAR(300) NOT NULL,
    addr2           VARCHAR(300),
    delivery_memo   VARCHAR(300),
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_address_member ON address (member_id);
-- 기본 배송지는 회원당 하나만 존재할 수 있다.
CREATE UNIQUE INDEX uq_address_default ON address (member_id) WHERE is_default;
