-- ============================================================
--  V3. 관리자 · 사이트 설정
-- ============================================================

CREATE TABLE admin_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'ADMIN'
                  CHECK (role IN ('ADMIN', 'SUPER_ADMIN')),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_count  INTEGER      NOT NULL DEFAULT 0,
    locked_until  TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- 누가 무엇을 언제 바꿨는지. 사고가 났을 때 이 기록이 유일한 단서가 된다.
CREATE TABLE admin_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 관리자 계정이 지워져도 로그는 남아야 한다.
    admin_id    BIGINT       REFERENCES admin_user (id) ON DELETE SET NULL,
    admin_name  VARCHAR(100) NOT NULL,
    action      VARCHAR(60)  NOT NULL,
    target_type VARCHAR(60)  NOT NULL,
    target_id   VARCHAR(60),
    summary     VARCHAR(500),
    ip          VARCHAR(64),
    user_agent  VARCHAR(300),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_created ON admin_audit_log (created_at DESC);
CREATE INDEX idx_audit_target  ON admin_audit_log (target_type, target_id);


-- 푸터 사업자정보, SNS 링크, 메인 섹션 노출 여부 등.
-- 코드에 박지 않고 대표가 관리자 화면에서 바꾼다.
CREATE TABLE site_setting (
    key         VARCHAR(100) PRIMARY KEY,
    value       TEXT,
    description VARCHAR(300),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
