-- ============================================================
--  V4. 배너 · 공지사항
-- ============================================================

CREATE TABLE banner (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 관리용 제목. 화면에는 나오지 않는다.
    title            VARCHAR(200) NOT NULL,
    -- PC 와 모바일 이미지를 따로 받는다. 하나로 쓰면 어느 한쪽이 반드시 깨진다.
    image_pc_key     VARCHAR(500) NOT NULL,
    image_mobile_key VARCHAR(500) NOT NULL,
    -- 접근성 필수. 비워둘 수 없다.
    alt_text         VARCHAR(300) NOT NULL,
    link_url         VARCHAR(1000),
    position         VARCHAR(30)  NOT NULL
                     CHECK (position IN ('MAIN_TOP', 'MAIN_MID', 'PRODUCT_TOP')),
    open_new_tab     BOOLEAN      NOT NULL DEFAULT FALSE,
    -- always_on 이 false 면 start_at ~ end_at 구간에만 노출된다.
    always_on        BOOLEAN      NOT NULL DEFAULT TRUE,
    start_at         TIMESTAMPTZ,
    end_at           TIMESTAMPTZ,
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    visible          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT banner_period_valid
        CHECK (always_on OR (start_at IS NOT NULL AND end_at IS NOT NULL AND start_at < end_at))
);

CREATE INDEX idx_banner_position ON banner (position, sort_order) WHERE visible;


CREATE TABLE notice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category     VARCHAR(20)  NOT NULL DEFAULT 'NOTICE'
                 CHECK (category IN ('NOTICE', 'EVENT', 'INFO')),
    title        VARCHAR(300) NOT NULL,
    -- 에디터 입력. 서버에서 HTML 살균한 결과만 들어간다.
    body_html    TEXT         NOT NULL,
    is_pinned    BOOLEAN      NOT NULL DEFAULT FALSE,
    view_count   INTEGER      NOT NULL DEFAULT 0,
    -- 미래 시각을 넣으면 그때까지 공개되지 않는다 (발행 예약).
    published_at TIMESTAMPTZ,
    visible      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_notice_list ON notice (is_pinned DESC, published_at DESC) WHERE visible;


CREATE TABLE notice_file (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id     BIGINT       NOT NULL REFERENCES notice (id) ON DELETE CASCADE,
    file_key      VARCHAR(500) NOT NULL,
    original_name VARCHAR(300) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    content_type  VARCHAR(120),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_notice_file_notice ON notice_file (notice_id);
