-- ============================================================
--  V5. 배송비 정책 · 장바구니 · 위시리스트
--  금액은 전부 원 단위 정수다.
-- ============================================================

-- 무료배송 임계액을 코드에 박지 않는다. 대표가 관리자 화면에서 바꾼다.
CREATE TABLE shipping_policy (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    base_fee         INTEGER      NOT NULL CHECK (base_fee >= 0),
    -- 이 금액 이상이면 배송비가 0 이 된다. NULL 이면 무료배송 없음.
    free_threshold   INTEGER      CHECK (free_threshold > 0),
    island_extra_fee INTEGER      NOT NULL DEFAULT 0 CHECK (island_extra_fee >= 0),
    visible          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 활성 정책은 하나만 둔다. 여러 개가 활성이면 어느 것을 쓸지 모호해진다.
CREATE UNIQUE INDEX uq_shipping_policy_active ON shipping_policy ((TRUE)) WHERE visible;


-- 비회원도 담을 수 있다. 비회원은 guest_token 으로 식별하고,
-- 로그인하면 회원 장바구니에 병합한 뒤 게스트 행을 지운다.
CREATE TABLE cart (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT      REFERENCES member (id) ON DELETE CASCADE,
    -- 추측 불가능한 UUID. HttpOnly 쿠키로만 주고받는다.
    guest_token VARCHAR(64),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 회원 장바구니이거나 게스트 장바구니이거나, 둘 중 하나여야 한다.
    CONSTRAINT cart_owner_exactly_one
        CHECK ((member_id IS NOT NULL AND guest_token IS NULL)
            OR (member_id IS NULL AND guest_token IS NOT NULL))
);

CREATE UNIQUE INDEX uq_cart_member ON cart (member_id)   WHERE member_id IS NOT NULL;
CREATE UNIQUE INDEX uq_cart_guest  ON cart (guest_token) WHERE guest_token IS NOT NULL;
-- 오래된 게스트 장바구니를 정리하는 배치가 이 인덱스를 쓴다.
CREATE INDEX idx_cart_guest_stale ON cart (updated_at) WHERE guest_token IS NOT NULL;


CREATE TABLE cart_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id           BIGINT      NOT NULL REFERENCES cart (id) ON DELETE CASCADE,
    product_id        BIGINT      NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    product_option_id BIGINT      REFERENCES product_option (id) ON DELETE CASCADE,
    quantity          INTEGER     NOT NULL CHECK (quantity > 0),
    added_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 같은 상품·옵션을 두 줄로 담지 않는다. 이미 있으면 수량을 더한다.
-- 옵션이 없는 경우도 하나로 묶기 위해 COALESCE 표현식 인덱스를 쓴다.
CREATE UNIQUE INDEX uq_cart_item
    ON cart_item (cart_id, product_id, COALESCE(product_option_id, -1));
CREATE INDEX idx_cart_item_cart ON cart_item (cart_id);


CREATE TABLE wishlist_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT      NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    product_id BIGINT      NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (member_id, product_id)
);

CREATE INDEX idx_wishlist_member ON wishlist_item (member_id, created_at DESC);
