-- ============================================================
--  V6. 주문
--
--  주문에 들어가는 금액은 절대 클라이언트가 보낸 값을 쓰지 않는다.
--  서버가 상품 테이블을 다시 읽어 계산한 결과만 여기 남는다.
--
--  배송지·수령인·상품명·가격을 주문 시점 값으로 박아둔다.
--  회원이 주소를 바꾸거나 상품이 수정돼도 주문 기록은 그대로여야 한다.
-- ============================================================

CREATE TABLE orders (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 화면과 URL 에 노출되는 주문번호.
    -- 순번을 쓰면 남의 주문을 훑을 수 있으므로 추측 불가능해야 한다.
    order_no                 VARCHAR(40)  NOT NULL UNIQUE,
    -- 비회원 주문을 허용하므로 nullable. 회원이 탈퇴해도 주문은 남는다.
    member_id                BIGINT       REFERENCES member (id) ON DELETE SET NULL,

    status                   VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                             CHECK (status IN ('PENDING', 'PAID', 'PREPARING', 'SHIPPED',
                                               'DELIVERED', 'CANCELLED', 'REFUNDED')),

    orderer_name             VARCHAR(100) NOT NULL,
    orderer_phone_encrypted  VARCHAR(500) NOT NULL,
    orderer_email            VARCHAR(320),

    receiver_name            VARCHAR(100) NOT NULL,
    receiver_phone_encrypted VARCHAR(500) NOT NULL,
    zipcode                  VARCHAR(10)  NOT NULL,
    addr1                    VARCHAR(300) NOT NULL,
    addr2                    VARCHAR(300),
    delivery_memo            VARCHAR(300),

    items_amount             INTEGER      NOT NULL CHECK (items_amount >= 0),
    shipping_fee             INTEGER      NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
    discount_amount          INTEGER      NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount             INTEGER      NOT NULL CHECK (total_amount >= 0),

    ordered_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    paid_at                  TIMESTAMPTZ,
    cancelled_at             TIMESTAMPTZ,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- 전자상거래법상 거래기록 보존기간이 지나면 파기한다.
    purge_at                 TIMESTAMPTZ,

    -- 합계가 맞지 않는 주문이 저장되는 것을 DB 차원에서 막는다.
    CONSTRAINT orders_total_matches
        CHECK (total_amount = items_amount + shipping_fee - discount_amount)
);

CREATE INDEX idx_orders_member ON orders (member_id, ordered_at DESC);
CREATE INDEX idx_orders_status ON orders (status, ordered_at DESC);
CREATE INDEX idx_orders_purge  ON orders (purge_at) WHERE purge_at IS NOT NULL;


CREATE TABLE order_item (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    -- 상품이 지워져도 주문 항목은 남는다. 이름은 아래 스냅샷 컬럼에 있다.
    product_id             BIGINT       REFERENCES product (id) ON DELETE SET NULL,
    product_option_id      BIGINT       REFERENCES product_option (id) ON DELETE SET NULL,

    product_name_snapshot  VARCHAR(200) NOT NULL,
    option_name_snapshot   VARCHAR(120),
    thumbnail_key_snapshot VARCHAR(500),
    unit_price_snapshot    INTEGER      NOT NULL CHECK (unit_price_snapshot >= 0),

    quantity               INTEGER      NOT NULL CHECK (quantity > 0),
    line_amount            INTEGER      NOT NULL CHECK (line_amount >= 0),

    CONSTRAINT order_item_line_matches
        CHECK (line_amount = unit_price_snapshot * quantity)
);

CREATE INDEX idx_order_item_order   ON order_item (order_id);
CREATE INDEX idx_order_item_product ON order_item (product_id);
