-- ============================================================
--  V7. 결제 · 배송 · 취소반품교환 · 재고 원장
-- ============================================================

-- PG 사가 아직 확정되지 않았으므로 특정 업체에 종속되지 않는 형태로 둔다.
-- 포트원을 쓰든 다른 곳을 쓰든 pg_provider 값과 어댑터 구현만 바뀐다.
CREATE TABLE payment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    pg_provider  VARCHAR(40)  NOT NULL,
    -- PG 가 발급한 거래 고유번호. 취소와 조회에 쓴다.
    pg_tid       VARCHAR(200),
    method       VARCHAR(40),
    amount       INTEGER      NOT NULL CHECK (amount >= 0),
    status       VARCHAR(20)  NOT NULL DEFAULT 'READY'
                 CHECK (status IN ('READY', 'PAID', 'FAILED',
                                   'CANCELLED', 'PARTIAL_CANCELLED')),
    approved_at  TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    receipt_url  VARCHAR(1000),
    fail_reason  VARCHAR(500),
    -- PG 원본 응답. 분쟁이 나면 이 기록이 근거가 된다.
    raw_response JSONB,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_payment_tid ON payment (pg_provider, pg_tid) WHERE pg_tid IS NOT NULL;
CREATE INDEX idx_payment_order ON payment (order_id);


CREATE TABLE delivery (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT      NOT NULL UNIQUE REFERENCES orders (id) ON DELETE CASCADE,
    carrier      VARCHAR(60),
    tracking_no  VARCHAR(100),
    status       VARCHAR(20) NOT NULL DEFAULT 'READY'
                 CHECK (status IN ('READY', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED')),
    shipped_at   TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- 전자상거래법상 청약철회 이력이다.
-- 분쟁이 생기면 이 기록이 근거가 되므로 요청 시각과 처리 시각을 반드시 남긴다.
CREATE TABLE order_claim (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    type          VARCHAR(20) NOT NULL
                  CHECK (type IN ('CANCEL', 'RETURN', 'EXCHANGE')),
    reason_code   VARCHAR(40) NOT NULL,
    reason_text   VARCHAR(1000),
    status        VARCHAR(20) NOT NULL DEFAULT 'REQUESTED'
                  CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED')),
    refund_amount INTEGER     CHECK (refund_amount >= 0),
    admin_memo    VARCHAR(1000),
    requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_claim_order  ON order_claim (order_id);
CREATE INDEX idx_order_claim_status ON order_claim (status, requested_at DESC);


-- 재고가 왜 이 숫자가 됐는지 추적하기 위한 증감 이력이다.
-- 차감 자체는 product 를 원자적으로 UPDATE 하고 그 결과를 여기 한 줄 남긴다.
CREATE TABLE stock_ledger (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT      NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    product_option_id BIGINT      REFERENCES product_option (id) ON DELETE CASCADE,
    -- 음수면 차감, 양수면 입고
    delta             INTEGER     NOT NULL CHECK (delta <> 0),
    balance_after     INTEGER     NOT NULL CHECK (balance_after >= 0),
    reason            VARCHAR(40) NOT NULL
                      CHECK (reason IN ('ORDER', 'CANCEL', 'RETURN', 'RESTOCK', 'ADJUST')),
    order_id          BIGINT      REFERENCES orders (id) ON DELETE SET NULL,
    memo              VARCHAR(300),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_stock_ledger_product ON stock_ledger (product_id, created_at DESC);
CREATE INDEX idx_stock_ledger_order   ON stock_ledger (order_id);
