-- ============================================================
--  V8. 후기 · 문의
--
--  후기도 광고 규제 대상이다 (기획서 §9).
--  사용자가 쓴 글이라도 효능을 단정하는 표현은 노출 전 검토·편집한다.
--  그래서 visible 기본값이 false 이고, 관리자가 확인해야 공개된다.
-- ============================================================

CREATE TABLE review (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    member_id         BIGINT       REFERENCES member (id) ON DELETE SET NULL,
    -- 실제 주문 항목과 연결한다. 이 값이 있어야 구매자 인증 배지를 붙일 수 있다.
    order_item_id     BIGINT       UNIQUE REFERENCES order_item (id) ON DELETE SET NULL,

    rating            SMALLINT     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content           TEXT         NOT NULL,
    -- 탈퇴해도 후기는 남으므로 작성자 표시용 이름을 따로 박아둔다.
    author_name       VARCHAR(100) NOT NULL,

    verified_purchase BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 체험단·협찬 후기는 광고 표시가 법적 의무다.
    is_sponsored      BOOLEAN      NOT NULL DEFAULT FALSE,

    -- 관리자가 확인하기 전에는 공개되지 않는다.
    visible           BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden_reason     VARCHAR(300),

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_review_product ON review (product_id, created_at DESC) WHERE visible;
CREATE INDEX idx_review_member  ON review (member_id, created_at DESC);
CREATE INDEX idx_review_pending ON review (created_at DESC) WHERE NOT visible;


CREATE TABLE review_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id  BIGINT       NOT NULL REFERENCES review (id) ON DELETE CASCADE,
    image_key  VARCHAR(500) NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_review_image_review ON review_image (review_id, sort_order);


CREATE TABLE inquiry (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT       REFERENCES member (id) ON DELETE SET NULL,
    type            VARCHAR(20)  NOT NULL DEFAULT 'GENERAL'
                    CHECK (type IN ('GENERAL', 'WHOLESALE', 'PARTNERSHIP', 'ORDER')),
    -- 주문 관련 문의는 해당 주문을 연결한다.
    order_id        BIGINT       REFERENCES orders (id) ON DELETE SET NULL,

    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(320) NOT NULL,
    phone_encrypted VARCHAR(500),
    message         TEXT         NOT NULL,

    answer          TEXT,
    answered_at     TIMESTAMPTZ,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING', 'ANSWERED', 'CLOSED')),

    -- 개인정보 수집 동의 시각과 파기 예정일. 법적 의무다.
    consent_at      TIMESTAMPTZ  NOT NULL,
    purge_at        TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_inquiry_status ON inquiry (status, created_at DESC);
CREATE INDEX idx_inquiry_member ON inquiry (member_id, created_at DESC);
CREATE INDEX idx_inquiry_purge  ON inquiry (purge_at) WHERE purge_at IS NOT NULL;
