-- ============================================================
--  V9. 이벤트 · 쿠폰  (구조만 세워둔다)
--
--  요건이 확정되지 않았다. 지금은 테이블만 만들고 화면과 API 는 붙이지 않는다.
--  나중에 정책이 정해지면 컬럼을 더하는 대신 이 구조 안에서 해결되도록,
--  할인 방식을 정률/정액 두 가지로만 두고 조건은 최소한으로 잡았다.
-- ============================================================

CREATE TABLE event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(300) NOT NULL,
    slug          VARCHAR(120) NOT NULL UNIQUE,
    -- 에디터 입력. 서버에서 HTML 살균한 결과만 들어간다.
    body_html     TEXT,
    thumbnail_key VARCHAR(500),
    banner_pc_key VARCHAR(500),
    banner_mo_key VARCHAR(500),
    alt_text      VARCHAR(300),
    start_at      TIMESTAMPTZ  NOT NULL,
    end_at        TIMESTAMPTZ  NOT NULL,
    visible       BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT event_period_valid CHECK (start_at < end_at)
);

CREATE INDEX idx_event_period ON event (start_at, end_at) WHERE visible;


CREATE TABLE coupon (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         BIGINT       REFERENCES event (id) ON DELETE SET NULL,
    name             VARCHAR(200) NOT NULL,
    -- 코드가 있으면 사용자가 직접 입력해 받는 쿠폰, 없으면 발급형이다.
    code             VARCHAR(60)  UNIQUE,

    discount_type    VARCHAR(20)  NOT NULL
                     CHECK (discount_type IN ('PERCENT', 'AMOUNT')),
    discount_value   INTEGER      NOT NULL CHECK (discount_value > 0),
    -- 정률 할인의 상한. 10% 할인이되 최대 5000원 같은 식.
    max_discount     INTEGER      CHECK (max_discount > 0),
    -- 최소 주문 금액
    min_order_amount INTEGER      NOT NULL DEFAULT 0 CHECK (min_order_amount >= 0),

    -- 전체 발급 한도와 1인당 발급 한도. NULL 이면 무제한.
    total_quantity   INTEGER      CHECK (total_quantity > 0),
    issued_count     INTEGER      NOT NULL DEFAULT 0 CHECK (issued_count >= 0),
    per_member_limit INTEGER      NOT NULL DEFAULT 1 CHECK (per_member_limit > 0),

    start_at         TIMESTAMPTZ  NOT NULL,
    end_at           TIMESTAMPTZ  NOT NULL,
    -- 발급일로부터 며칠간 유효한지. NULL 이면 end_at 까지.
    valid_days       INTEGER      CHECK (valid_days > 0),

    visible          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT coupon_period_valid CHECK (start_at < end_at),
    -- 정률 할인은 100%를 넘을 수 없다.
    CONSTRAINT coupon_percent_range
        CHECK (discount_type <> 'PERCENT' OR discount_value <= 100)
);


-- 회원에게 발급된 쿠폰 한 장.
CREATE TABLE coupon_issue (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id  BIGINT      NOT NULL REFERENCES coupon (id) ON DELETE CASCADE,
    member_id  BIGINT      NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    -- 사용되면 어느 주문에 쓰였는지 남긴다.
    order_id   BIGINT      REFERENCES orders (id) ON DELETE SET NULL,
    used_at    TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    issued_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_coupon_issue_member ON coupon_issue (member_id, used_at);
-- 한 주문에 같은 쿠폰이 두 번 적용되지 않게 한다.
CREATE UNIQUE INDEX uq_coupon_issue_order ON coupon_issue (order_id) WHERE order_id IS NOT NULL;
